// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbnvgfppwygqvjypaevu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZibnZnZnBwd3lncXZqeXBhZXZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwOTUxMzQsImV4cCI6MjA2NTY3MTEzNH0.-AvBFfj8NyQMERFTg68YV5fT6Ixi6navUxUgfB2ssL0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);